GET http://localhost:3001/info
###
GET http://localhost:3001/api/persons
###
GET http://localhost:3001/api/persons/3
###
GET http://localhost:3001/api/persons/6462d78c7ded871ba6cb4147
###
GET http://localhost:3001/api/persons/6462d78c7ded871ba6cb4146
###
DELETE http://localhost:3001/api/persons/4
###
DELETE http://localhost:3001/api/persons/6462d7fcbebeedf2a8d10334
###
POST http://localhost:3001/api/persons
content-type: application/json

{
    "name": "Test User",
    "number": "123-123-1235"
}
###
POST http://localhost:3001/api/persons
content-type: application/json

{
    "number": "123-123-1234"
}
###
POST http://localhost:3001/api/persons
content-type: application/json

{
    "name": "Test User"
}